version: '3'
services:
  web01:
    build:
      context: ./web01
      dockerfile: Dockerfile.dockerfile
    image: web01
    container_name: web01
    restart: always
    tty: true
    ports:
      - "8080:80"
    networks:
      - asa-network

  web02:
    build:
      context: ./web02
      dockerfile: Dockerfile.dockerfile
    image: web02
    container_name: web02
    restart: always
    tty: true
    ports:
      - "8081:80"
    networks:
      - asa-network

#proxy:
  #build:
    #context: .

#Docker Networks
networks:
  asa-network:
    driver: bridge
